language: python

python:
 - "2.7_with_system_site_packages"

before_install:

  # Installing packages with apt-get is much faster than with pip.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

  # Install `xy_python_utils`.
  - git clone https://github.com/yxiong/xy_python_utils
  - cd xy_python_utils
  - pip install -r requirements.txt
  - python setup.py develop
  - cd ..


install:
  - pip install -r requirements.txt
  - python setup.py develop


script:
  - cd xy_color
  - python -m unittest discover -p "*_test.py"
  - cd ..

  - cd docs
  - make html
  - cd ..
